name = "ICA_BlindSourceSeparation"
uuid = "822b78d8-c4d8-4e4d-8607-4515e2b6a9d9"
authors = ["Erik Felgendreher felgendreher@campus.tu-berlin.de"]
version = "1.0.0-DEV"

[deps]
Cumulants = "01e79fc4-f247-5fa3-af0e-2bd1d4cc767f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
Cumulants = "1.0.6"
LinearAlgebra = "1.11.0"
Plots = "1.40.16"
Statistics = "1.11.1"
PyPlot = "2.11"
julia = "1.11"
